# NUMPY EGZERSİZLERİ

# Array oluşturma

#### Import numpy as np (Numpy ı yükleyin )

In [1]:
import numpy as np

### ([1,2,3,4,5]) elemanlarından oluşan bir array tanımlayın

In [6]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

### 0 lardan oluşan 4 satırlı 5 sütunlu bir array oluşturun

In [15]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 7 lerden oluşan 3 satırlı  5 sütunlu bir array oluşturun

In [17]:
np.ones((3,5))*7

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

### 10 dan başlayarak 70 e kadar 5 er artan bir array oluşturun ( arange( ) fonksiyonunu kullanın)

In [18]:
np.arange(10,70,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

### 0 ile 5 arasında 15 tane aynı uzaklıkta elemanı olan bir array oluşturun( linspace( ) fonksiyonunu kullanın)

In [19]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

### Normal dağılımda 3 satır 5 sütunlu bir array oluşturun ( random.randn( ) )

In [22]:
np.random.randn(3,5)

array([[ 1.3325519 ,  0.48768126,  1.15380951, -0.69157292, -0.8202199 ],
       [-1.64918142, -0.45773118,  0.43879256,  1.63338692, -1.07378123],
       [ 0.97844108, -0.24417337, -0.82110897,  0.35469608,  1.66997855]])

### 5 elemanlı birim matris oluşturun ( eye( ) )

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 0 dan 24 e kadar sayıların olduğu bir array oluşturun ve reshape() metodunu kullanarak 4 satır ve 6 sütunlu hale getirin.

In [31]:
np.arange(24).reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### 0 ile 1 arasında rastgele 10 sayıdan oluşan bir array tanımlayıp en düşük ve en yüksek değerleri tespit edin.

In [40]:
b = np.random.rand(5)
b

array([0.05397186, 0.0948155 , 0.95083666, 0.83186621, 0.2530974 ])

In [41]:
b.max()

0.9508366636996349

In [42]:
b.min()

0.053971856700130605

# Numpy indeksleme ve iterasyon



### Rastgele 16 sayıdan oluşan ve 4 satır 4 sütunlu bir array oluşturun

In [54]:
k = np.random.random(16).reshape(4,4)
k

array([[0.10880446, 0.66753419, 0.2662715 , 0.90564447],
       [0.69084488, 0.66599269, 0.13765094, 0.06562448],
       [0.89364482, 0.23163563, 0.65546452, 0.31479013],
       [0.47279325, 0.95100949, 0.40295584, 0.6357508 ]])

### 2.satır daki tüm elemanları çekin

In [56]:
k[1:2,]

array([[0.69084488, 0.66599269, 0.13765094, 0.06562448]])

### 4 üncü satır 4 üncü sütundaki sayıyı çekin

In [61]:
k[3,3]

0.6357508001482208

### 4 üncü sütundaki bütün elemanları çekin

In [63]:
k[:,3:4]

array([[0.90564447],
       [0.06562448],
       [0.31479013],
       [0.6357508 ]])

### For döngüsünü kullanarak oluşturduğunuz 16 sayıdan oluşan array in sayılarını alt alta flat() metodunu kullanarak yazdırın

In [75]:
for i in k.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


# Numpy işlemler

### 0 ile 1 arasında Rastgele 4 sayıdan oluşan bir array oluşturun ve her sayıyı 5 ile çarpın

In [80]:
o = np.random.random(4)*5

### Oluşturduğunuz array in sayılarının toplamını bulun

In [81]:
sum(o)

5.468229576242107

### Oluşturduğunuz array in standart sapmasını bulun

In [82]:
np.std(o)

1.1625119167319353

### Oluşturduğunuz array in varyansını bulun

In [83]:
np.var(o)

1.3514339565437583