# NUMPY

### Kütüphaneyi import etme

In [4]:
import numpy as np

##### Array Oluşturma

In [7]:
x = np.array([1,2,3,4,5])

In [8]:
type(x)

numpy.ndarray

###### Zeros (Sıfırlardan oluşan aray)

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

###### Ones (Birlerden oluşan Array)

In [12]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones([2,4])*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [15]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
ondalik = np.arange(0,2,0.2)
ondalik

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [20]:
lin = np.linspace(0,4,12)
lin

array([0.        , 0.36363636, 0.72727273, 1.09090909, 1.45454545,
       1.81818182, 2.18181818, 2.54545455, 2.90909091, 3.27272727,
       3.63636364, 4.        ])