# NUMPY

### Kütüphaneyi import etme

In [4]:
import numpy as np

##### Array Oluşturma

In [7]:
x = np.array([1,2,3,4,5])

In [8]:
type(x)

numpy.ndarray

###### Zeros (Sıfırlardan oluşan aray)

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

###### Ones (Birlerden oluşan Array)

In [12]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

###### Ones matrix hangi sayıyla çarpılırsa matrixin elemanları o sayı olur

In [13]:
np.ones([2,4])*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

###### Arange fonksiyonu girilen 2 sayı aralıgında matrix oluşturur. 3. girilen veri kaçar kaçar aralıklardan oluştuğunu belirtir.

In [15]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
ondalik = np.arange(0,2,0.2)
ondalik

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

###### linspace fonksiyonunda girilen 2 değer arasını, girilen 3. değer  kadar eş parçaya bölüp matrix oluşturmaya yarar

In [22]:
lin = np.linspace(0,4,4)
lin

array([0.        , 1.33333333, 2.66666667, 4.        ])

###### Random sayı üreterek matris oluşturmak için: random.rand() fonksiyonu

In [25]:
rast = np.random.rand(3,4)
rast

array([[0.18151369, 0.03378811, 0.35284178, 0.01780236],
       [0.02097034, 0.64086964, 0.18640139, 0.54574873],
       [0.34153143, 0.61394055, 0.33467035, 0.20509059]])

###### Eksi (-) sayılarıda alarak random matrix oluşturma : randon.randn()

In [28]:
n = np.random.randn(2,3)
n

array([[ 0.88112104,  0.21090253, -0.14530411],
       [-0.76745454, -1.00945697, -1.65991443]])

In [30]:
#5katını alma
n = np.random.randn(2,3)*5
n

array([[-0.55122568,  0.77411465, -9.60172201],
       [ 3.19947247,  2.61096481,  3.55479421]])

###### Birim matrix oluşturma

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.random.randint(1,50,4)

array([45, 36, 14, 39])

######  Arange fonk. ile oluşan matrixi, reshape fonk. ile satır sütun sayısı belirlenebilir

In [41]:
y = np.arange(24)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [40]:
y.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [44]:
y.reshape(2,2,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

###### Max , Min

In [60]:
c = np.random.randint(1,50, 12)
c

array([48, 43, 15, 19, 13, 26, 14, 26, 42, 31, 43, 31])

In [61]:
c.max()

48

In [62]:
c.min()

13

In [64]:
#max olan sayının indexini bulur
c.argmax()

0

In [65]:
#min olan sayının indexini bulur
c.argmin()

4

######  0'dan 50 e array oluşturulur. 
###### m.shape = 2 , -1, 5
###### demek; 2 matris oluştur
###### -1 : en uygun olanını bulur
###### uygun olarak bulduğu sayı ile girilen 5 sayısı satır ve sütun sayısılarını oluşturur

In [70]:
m = np.arange(50)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [73]:
m.shape = 2,-1,5
m.shape

(2, 5, 5)

In [74]:
m

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])