# NUMPY
## iŞLEMLER

In [1]:
import numpy as np

In [3]:
a = np.array([20,40,60,80])
a

array([20, 40, 60, 80])

In [4]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [5]:
c = a + b
c

array([20, 41, 62, 83])

In [12]:
#Array'in her elemanının karesi alınır
a**2

array([ 400, 1600, 3600, 6400], dtype=int32)

In [11]:
# Array her elemanı için 50'den büyük olup olmadgına bakar
a>50

array([False, False,  True,  True])

In [13]:
a +=10
a

array([30, 50, 70, 90])

In [15]:
s = np.random.random(12)
s

array([0.33558482, 0.0749512 , 0.95411985, 0.5235413 , 0.84215454,
       0.01063618, 0.67994908, 0.24051624, 0.06254847, 0.94319482,
       0.44151359, 0.35213834])

In [16]:
s.max()

0.9541198520109515

In [17]:
s.min()

0.010636179054188899

In [18]:
s.sum()

5.460848432038079

In [19]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

##### sütunları toplama : axis=0

In [20]:
b.sum(axis=0)

array([15, 18, 21, 24, 27])

#### satırları topla : axis = 1

In [21]:
b.sum(axis=1)

array([10, 35, 60])

#### b arrayinde satırda max sayıyı bulur 

In [23]:
b.max(axis = 1)

array([ 4,  9, 14])

#### b arrayinde sütunda max sayıyı bulur 

In [24]:
b.max(axis = 0)

array([10, 11, 12, 13, 14])

#### Cumsum func kümülatif toplama

In [25]:
b.cumsum(axis = 1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [28]:
k = np.random.rand(10)
k

array([0.21293821, 0.04264439, 0.06315079, 0.61163147, 0.10114143,
       0.88366922, 0.77431365, 0.99380316, 0.55532982, 0.25770514])

In [29]:
k.mean()

0.44963272730127424

In [32]:
#median'nını bulma
np.median(k)

0.4065174789735079

In [33]:
#Standart sapmasını bulma
np.std(k)

0.3400965708073435

In [34]:
#Varyansını bulma
np.var(k)

0.11566567747491444

In [35]:
copy = k.copy()
copy

array([0.21293821, 0.04264439, 0.06315079, 0.61163147, 0.10114143,
       0.88366922, 0.77431365, 0.99380316, 0.55532982, 0.25770514])

In [40]:
sehir = np.array(["ankara", "bursa", "bolu","ankara","bolu", "bolu"])
np.unique(sehir)

array(['ankara', 'bolu', 'bursa'], dtype='<U6')