# NUMPY 
### İndexleme

In [76]:
#import library
import numpy as np

### Tek Boyutlu Array

In [77]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
#karesii alma
arr = np.arange(10)**2
arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [82]:
# arr'in 3ç elemanını bulma
arr[3]

9

#### arr 'ın 3. indexten başlayarak 6.indexe kadar olan elemanlarını alma

In [83]:
arr[3:6]

array([ 9, 16, 25], dtype=int32)

In [84]:
arr[4]=1000
arr

array([   0,    1,    4,    9, 1000,   25,   36,   49,   64,   81],
      dtype=int32)

In [86]:
for i in arr:
    print(i*2)

0
2
8
18
2000
50
72
98
128
162


### Çok Boyutlu  Array 

In [98]:
y = np.random.rand(16)

y

array([0.13336741, 0.05259153, 0.26084642, 0.14416462, 0.55969165,
       0.77810166, 0.79308326, 0.90591364, 0.25233775, 0.53327963,
       0.10521097, 0.6979311 , 0.48685696, 0.20530067, 0.85233641,
       0.88488451])

In [103]:
y = y.reshape(4,4)

y

array([[0.13336741, 0.05259153, 0.26084642, 0.14416462],
       [0.55969165, 0.77810166, 0.79308326, 0.90591364],
       [0.25233775, 0.53327963, 0.10521097, 0.6979311 ],
       [0.48685696, 0.20530067, 0.85233641, 0.88488451]])

##### Shape yapılmış matrix arrayi eski haline döndürmek için Ravel() func.

In [100]:
y.ravel()

array([0.13336741, 0.05259153, 0.26084642, 0.14416462, 0.55969165,
       0.77810166, 0.79308326, 0.90591364, 0.25233775, 0.53327963,
       0.10521097, 0.6979311 , 0.48685696, 0.20530067, 0.85233641,
       0.88488451])

### y[0:2,1] Sıfırıncı satırdan başlayarak 2. satırı alsın ama sadece 1. sutünunu alsın

In [106]:
y[0:2,1]

array([0.05259153, 0.77810166])

### Bütun satırları alsın, 3. sütununu alsın

In [107]:
y[:,3]

array([0.14416462, 0.90591364, 0.6979311 , 0.88488451])

In [108]:
for satir in y:
    print(satir)

[0.13336741 0.05259153 0.26084642 0.14416462]
[0.55969165 0.77810166 0.79308326 0.90591364]
[0.25233775 0.53327963 0.10521097 0.6979311 ]
[0.48685696 0.20530067 0.85233641 0.88488451]


### Tüm elemanları tek satırda yazmak için Flat func yazılır

In [109]:
for satir in y.flat:
    print(satir)

0.1333674146101972
0.0525915288978811
0.26084641895974336
0.14416462422505483
0.5596916458003911
0.7781016584609494
0.7930832628402373
0.9059136391814573
0.25233774739816506
0.533279634680999
0.10521096937421603
0.6979310997257269
0.48685696338115203
0.20530066693031557
0.8523364060484714
0.8848845077154346


### elemanları indexleri ile bastırır

In [111]:
for satir in np.ndenumerate(y):
    print(satir)

((0, 0), 0.1333674146101972)
((0, 1), 0.0525915288978811)
((0, 2), 0.26084641895974336)
((0, 3), 0.14416462422505483)
((1, 0), 0.5596916458003911)
((1, 1), 0.7781016584609494)
((1, 2), 0.7930832628402373)
((1, 3), 0.9059136391814573)
((2, 0), 0.25233774739816506)
((2, 1), 0.533279634680999)
((2, 2), 0.10521096937421603)
((2, 3), 0.6979310997257269)
((3, 0), 0.48685696338115203)
((3, 1), 0.20530066693031557)
((3, 2), 0.8523364060484714)
((3, 3), 0.8848845077154346)


### Stack fonkciyonu
### 2 arrayi yanyana birleştirme : hstack()
### 2 arrayi alt alta birleştirme : vstack()

In [112]:
a = np.array([2,3])
b = np.array([5,6])
np.hstack((a,b))

array([2, 3, 5, 6])

In [113]:
np.vstack((a,b))

array([[2, 3],
       [5, 6]])

### 2 arrayi birleştirir, axis = 0 alt alta ekler

In [123]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### 2 arrayi birleştirir, axis=1 yanyana ekler, T : b matrixinin tersini alır

In [125]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])